Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import glob
from pymatgen.analysis.defects.finder import DefectSiteFinder
from pymatgen.core.structure import Structure

base_struct = Structure.from_file(
    "/Users/shen9/repos/mp/pymatgen-analysis-defects/tests/test_files/v_O_ZrO2/relax_2/CONTCAR"
)
finder = DefectSiteFinder()

for q in [-1, 0, 1, 2, 3]:
    fname = f"{str(TEST_FILES)}/v_O_ZrO2/relax_2_v_O_q={q}/CONTCAR"
    struct = Structure.from_file(fname)
    fpos = finder.get_defect_fpos(defect_structure=struct, base_structure=base_struct)
    fpos -= np.round(fpos)
    print(fpos)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01manalysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdefects[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfinder[39;00m [38;5;28;01mimport[39;00m DefectSiteFinder
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstructure[39;00m [38;5;28;01mimport[39;00m Structure
[0;32m----> 5[0m base_struct [38;5;241m=[39m [43mStructure[49m[38;5;241;43m.[39;49m[43mfrom_file[49m[43m([49m
[1;32m      6[0m [43m    [49m[38;5;124;43m"[39;49m[38;5;124;43m/Users/shen9/repos/mp/pymatgen-analysis-defects/tests/test_files/v_O_ZrO2/relax_2/CONTCAR[39;49m[38;5;124;43m"[39;49m
[1;32m      7[0m [43m)[49m
[1;32m      8[0m finder [38;5;241m=[39m DefectSiteFinder()
[1;32m     10[0m [38;5;28;01mfor[39;00m q [38;5;129;01min[39;00m [[38;5;241m-[39m[38;5;241m1[39m, [38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m3[39m]:

File [0;32m/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/pymatgen/core/structure.py:2682[0m, in [0;36mIStructure.from_file[0;34m(cls, filename, primitive, sort, merge_tol, **kwargs)[0m
[1;32m   2679[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvasp[39;00m [38;5;28;01mimport[39;00m Chgcar, Vasprun
[1;32m   2681[0m fname [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mbasename(filename)
[0;32m-> 2682[0m [38;5;28;01mwith[39;00m [43mzopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrt[39;49m[38;5;124;43m"[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m   2683[0m     contents [38;5;241m=[39m f[38;5;241m.[39mread()
[1;32m   2684[0m [38;5;28;01mif[39;00m fnmatch(fname[38;5;241m.[39mlower(), [38;5;124m"[39m[38;5;124m*.cif*[39m[38;5;124m"[39m) [38;5;129;01mor[39;00m fnmatch(fname[38;5;241m.[39mlower(), [38;5;124m"[39m[38;5;124m*.mcif*[39m[38;5;124m"[39m):

File [0;32m/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/monty/io.py:45[0m, in [0;36mzopen[0;34m(filename, *args, **kwargs)[0m
[1;32m     43[0m [38;5;28;01mif[39;00m ext [38;5;129;01min[39;00m ([38;5;124m"[39m[38;5;124m.XZ[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m.LZMA[39m[38;5;124m"[39m):
[1;32m     44[0m     [38;5;28;01mreturn[39;00m lzma[38;5;241m.[39mopen(filename, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m---> 45[0m [38;5;28;01mreturn[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/shen9/repos/mp/pymatgen-analysis-defects/tests/test_files/v_O_ZrO2/relax_2/CONTCAR'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shen9/repos/mp/pymatgen-analysis-defects/tests/test_files/v_O_ZrO2/relax_2/CONTCAR'

