Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pathlib import Path

import numpy as np
from matplotlib import pyplot as plt
from monty.io import reverse_readfile
from pymatgen.analysis.defects.corrections.freysoldt import (
    Locpot,
    get_freysoldt_correction,
    plot_plnr_avg,
)
from pymatgen.analysis.defects.finder import DefectSiteFinder

TEST_FILES = Path("../../../tests/test_files")
DEFECT_DIR = TEST_FILES / "v_N_GaN"
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmonty[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m [38;5;28;01mimport[39;00m reverse_readfile
[0;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01manalysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdefects[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcorrections[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfreysoldt[39;00m [38;5;28;01mimport[39;00m (
[1;32m      7[0m     Locpot,
[1;32m      8[0m     get_freysoldt_correction,
[1;32m      9[0m     plot_plnr_avg,
[1;32m     10[0m )
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01manalysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdefects[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfinder[39;00m [38;5;28;01mimport[39;00m DefectSiteFinder
[1;32m     13[0m TEST_FILES [38;5;241m=[39m Path([38;5;124m"[39m[38;5;124m../../../tests/test_files[39m[38;5;124m"[39m)

File [0;32m~/work/pymatgen-analysis-defects/pymatgen-analysis-defects/pymatgen/analysis/defects/corrections/freysoldt.py:12[0m
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mscipy[39;00m
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01manalysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdefects[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfinder[39;00m [38;5;28;01mimport[39;00m DefectSiteFinder
[0;32m---> 12[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01manalysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdefects[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m (
[1;32m     13[0m     CorrectionResult,
[1;32m     14[0m     QModel,
[1;32m     15[0m     ang_to_bohr,
[1;32m     16[0m     converge,
[1;32m     17[0m     eV_to_k,
[1;32m     18[0m     generate_reciprocal_vectors_squared,
[1;32m     19[0m     hart_to_ev,
[1;32m     20[0m )
[1;32m     21[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvasp[39;00m[38;5;21;01m.[39;00m[38;5;21;01moutputs[39;00m [38;5;28;01mimport[39;00m Locpot, VolumetricData
[1;32m     22[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m [38;5;28;01mimport[39;00m stats

File [0;32m~/work/pymatgen-analysis-defects/pymatgen-analysis-defects/pymatgen/analysis/defects/utils.py:21[0m
[1;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmonty[39;00m[38;5;21;01m.[39;00m[38;5;21;01mjson[39;00m [38;5;28;01mimport[39;00m MSONable
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnumpy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlinalg[39;00m [38;5;28;01mimport[39;00m norm
[0;32m---> 21[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01manalysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlocal_env[39;00m [38;5;28;01mimport[39;00m cn_opt_params
[1;32m     22[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01manalysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstructure_matcher[39;00m [38;5;28;01mimport[39;00m StructureMatcher
[1;32m     23[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpymatgen[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m [38;5;28;01mimport[39;00m Structure

[0;31mImportError[0m: cannot import name 'cn_opt_params' from 'pymatgen.analysis.local_env' (/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pymatgen/analysis/local_env.py)

